# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\clientinfomodal.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ClientInfoModal_2(object):
    def setupUi(self, ClientInfoModal_2):
        ClientInfoModal_2.setObjectName("ClientInfoModal_2")
        ClientInfoModal_2.setWindowModality(QtCore.Qt.ApplicationModal)
        ClientInfoModal_2.resize(568, 383)
        ClientInfoModal_2.setStyleSheet("")
        ClientInfoModal_2.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(ClientInfoModal_2)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(ClientInfoModal_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_6.setHorizontalSpacing(10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.CityInput = QtWidgets.QLineEdit(self.frame_5)
        self.CityInput.setMinimumSize(QtCore.QSize(0, 30))
        self.CityInput.setObjectName("CityInput")
        self.gridLayout_6.addWidget(self.CityInput, 0, 0, 1, 1)
        self.ZipInput = QtWidgets.QLineEdit(self.frame_5)
        self.ZipInput.setMinimumSize(QtCore.QSize(0, 30))
        self.ZipInput.setObjectName("ZipInput")
        self.gridLayout_6.addWidget(self.ZipInput, 0, 2, 1, 1)
        self.StateComboBox = QtWidgets.QComboBox(self.frame_5)
        self.StateComboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.StateComboBox.setObjectName("StateComboBox")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.gridLayout_6.addWidget(self.StateComboBox, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_5, 3, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_7.setHorizontalSpacing(10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.EmailInput = QtWidgets.QLineEdit(self.frame_6)
        self.EmailInput.setMinimumSize(QtCore.QSize(0, 30))
        self.EmailInput.setObjectName("EmailInput")
        self.gridLayout_7.addWidget(self.EmailInput, 0, 0, 1, 1)
        self.PhoneInput = QtWidgets.QLineEdit(self.frame_6)
        self.PhoneInput.setMinimumSize(QtCore.QSize(0, 30))
        self.PhoneInput.setObjectName("PhoneInput")
        self.gridLayout_7.addWidget(self.PhoneInput, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_6, 4, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_8.setHorizontalSpacing(10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.HomeSearchURLInput = QtWidgets.QLineEdit(self.frame_7)
        self.HomeSearchURLInput.setMinimumSize(QtCore.QSize(0, 30))
        self.HomeSearchURLInput.setObjectName("HomeSearchURLInput")
        self.gridLayout_8.addWidget(self.HomeSearchURLInput, 0, 2, 1, 1)
        self.HomeValueURLInput = QtWidgets.QLineEdit(self.frame_7)
        self.HomeValueURLInput.setMinimumSize(QtCore.QSize(0, 30))
        self.HomeValueURLInput.setObjectName("HomeValueURLInput")
        self.gridLayout_8.addWidget(self.HomeValueURLInput, 0, 1, 1, 1)
        self.BlogURLInput = QtWidgets.QLineEdit(self.frame_7)
        self.BlogURLInput.setMinimumSize(QtCore.QSize(0, 30))
        self.BlogURLInput.setObjectName("BlogURLInput")
        self.gridLayout_8.addWidget(self.BlogURLInput, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_7, 5, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.FirstNameInput = QtWidgets.QLineEdit(self.frame_2)
        self.FirstNameInput.setMinimumSize(QtCore.QSize(0, 30))
        self.FirstNameInput.setClearButtonEnabled(False)
        self.FirstNameInput.setObjectName("FirstNameInput")
        self.gridLayout_3.addWidget(self.FirstNameInput, 0, 0, 1, 1)
        self.LastNameInput = QtWidgets.QLineEdit(self.frame_2)
        self.LastNameInput.setMinimumSize(QtCore.QSize(0, 30))
        self.LastNameInput.setObjectName("LastNameInput")
        self.gridLayout_3.addWidget(self.LastNameInput, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.CompanyNameInput = QtWidgets.QLineEdit(self.frame_3)
        self.CompanyNameInput.setMinimumSize(QtCore.QSize(0, 30))
        self.CompanyNameInput.setObjectName("CompanyNameInput")
        self.gridLayout_4.addWidget(self.CompanyNameInput, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_5.setHorizontalSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Address1Input = QtWidgets.QLineEdit(self.frame_4)
        self.Address1Input.setMinimumSize(QtCore.QSize(0, 30))
        self.Address1Input.setObjectName("Address1Input")
        self.gridLayout_5.addWidget(self.Address1Input, 0, 0, 1, 1)
        self.Address2Input = QtWidgets.QLineEdit(self.frame_4)
        self.Address2Input.setMinimumSize(QtCore.QSize(0, 30))
        self.Address2Input.setObjectName("Address2Input")
        self.gridLayout_5.addWidget(self.Address2Input, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 2, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.SaveBtn = QtWidgets.QPushButton(self.frame_9)
        self.SaveBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.SaveBtn.setFlat(False)
        self.SaveBtn.setObjectName("SaveBtn")
        self.gridLayout_10.addWidget(self.SaveBtn, 0, 1, 1, 1)
        self.CancelBtn = QtWidgets.QPushButton(self.frame_9)
        self.CancelBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.CancelBtn.setObjectName("CancelBtn")
        self.gridLayout_10.addWidget(self.CancelBtn, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_9, 7, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_9.setHorizontalSpacing(10)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.HexColorInput = QtWidgets.QLineEdit(self.frame_8)
        self.HexColorInput.setMinimumSize(QtCore.QSize(0, 30))
        self.HexColorInput.setObjectName("HexColorInput")
        self.gridLayout_9.addWidget(self.HexColorInput, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_8, 6, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(ClientInfoModal_2)
        QtCore.QMetaObject.connectSlotsByName(ClientInfoModal_2)
        ClientInfoModal_2.setTabOrder(self.FirstNameInput, self.LastNameInput)
        ClientInfoModal_2.setTabOrder(self.LastNameInput, self.CompanyNameInput)
        ClientInfoModal_2.setTabOrder(self.CompanyNameInput, self.Address1Input)
        ClientInfoModal_2.setTabOrder(self.Address1Input, self.Address2Input)
        ClientInfoModal_2.setTabOrder(self.Address2Input, self.CityInput)
        ClientInfoModal_2.setTabOrder(self.CityInput, self.StateComboBox)
        ClientInfoModal_2.setTabOrder(self.StateComboBox, self.ZipInput)
        ClientInfoModal_2.setTabOrder(self.ZipInput, self.EmailInput)
        ClientInfoModal_2.setTabOrder(self.EmailInput, self.PhoneInput)
        ClientInfoModal_2.setTabOrder(self.PhoneInput, self.BlogURLInput)
        ClientInfoModal_2.setTabOrder(self.BlogURLInput, self.HomeValueURLInput)
        ClientInfoModal_2.setTabOrder(self.HomeValueURLInput, self.HomeSearchURLInput)
        ClientInfoModal_2.setTabOrder(self.HomeSearchURLInput, self.HexColorInput)
        ClientInfoModal_2.setTabOrder(self.HexColorInput, self.SaveBtn)
        ClientInfoModal_2.setTabOrder(self.SaveBtn, self.CancelBtn)

    def retranslateUi(self, ClientInfoModal_2):
        _translate = QtCore.QCoreApplication.translate
        ClientInfoModal_2.setWindowTitle(_translate("ClientInfoModal_2", "Client Infomation"))
        self.CityInput.setPlaceholderText(_translate("ClientInfoModal_2", "City"))
        self.ZipInput.setPlaceholderText(_translate("ClientInfoModal_2", "Zip"))
        self.StateComboBox.setItemText(0, _translate("ClientInfoModal_2", "State"))
        self.StateComboBox.setItemText(1, _translate("ClientInfoModal_2", "AL"))
        self.StateComboBox.setItemText(2, _translate("ClientInfoModal_2", "AK"))
        self.StateComboBox.setItemText(3, _translate("ClientInfoModal_2", "AZ"))
        self.StateComboBox.setItemText(4, _translate("ClientInfoModal_2", "AR"))
        self.StateComboBox.setItemText(5, _translate("ClientInfoModal_2", "CA"))
        self.StateComboBox.setItemText(6, _translate("ClientInfoModal_2", "CO"))
        self.StateComboBox.setItemText(7, _translate("ClientInfoModal_2", "CT"))
        self.StateComboBox.setItemText(8, _translate("ClientInfoModal_2", "DC"))
        self.StateComboBox.setItemText(9, _translate("ClientInfoModal_2", "DE"))
        self.StateComboBox.setItemText(10, _translate("ClientInfoModal_2", "FL"))
        self.StateComboBox.setItemText(11, _translate("ClientInfoModal_2", "GA"))
        self.StateComboBox.setItemText(12, _translate("ClientInfoModal_2", "HI"))
        self.StateComboBox.setItemText(13, _translate("ClientInfoModal_2", "ID"))
        self.StateComboBox.setItemText(14, _translate("ClientInfoModal_2", "IL"))
        self.StateComboBox.setItemText(15, _translate("ClientInfoModal_2", "IN"))
        self.StateComboBox.setItemText(16, _translate("ClientInfoModal_2", "IA"))
        self.StateComboBox.setItemText(17, _translate("ClientInfoModal_2", "KS"))
        self.StateComboBox.setItemText(18, _translate("ClientInfoModal_2", "KY"))
        self.StateComboBox.setItemText(19, _translate("ClientInfoModal_2", "LA"))
        self.StateComboBox.setItemText(20, _translate("ClientInfoModal_2", "ME"))
        self.StateComboBox.setItemText(21, _translate("ClientInfoModal_2", "MD"))
        self.StateComboBox.setItemText(22, _translate("ClientInfoModal_2", "MA"))
        self.StateComboBox.setItemText(23, _translate("ClientInfoModal_2", "MI"))
        self.StateComboBox.setItemText(24, _translate("ClientInfoModal_2", "MN"))
        self.StateComboBox.setItemText(25, _translate("ClientInfoModal_2", "MS"))
        self.StateComboBox.setItemText(26, _translate("ClientInfoModal_2", "MO"))
        self.StateComboBox.setItemText(27, _translate("ClientInfoModal_2", "MT"))
        self.StateComboBox.setItemText(28, _translate("ClientInfoModal_2", "NE"))
        self.StateComboBox.setItemText(29, _translate("ClientInfoModal_2", "NV"))
        self.StateComboBox.setItemText(30, _translate("ClientInfoModal_2", "NH"))
        self.StateComboBox.setItemText(31, _translate("ClientInfoModal_2", "NJ"))
        self.StateComboBox.setItemText(32, _translate("ClientInfoModal_2", "NM"))
        self.StateComboBox.setItemText(33, _translate("ClientInfoModal_2", "NY"))
        self.StateComboBox.setItemText(34, _translate("ClientInfoModal_2", "NC"))
        self.StateComboBox.setItemText(35, _translate("ClientInfoModal_2", "ND"))
        self.StateComboBox.setItemText(36, _translate("ClientInfoModal_2", "OH"))
        self.StateComboBox.setItemText(37, _translate("ClientInfoModal_2", "OK"))
        self.StateComboBox.setItemText(38, _translate("ClientInfoModal_2", "OR"))
        self.StateComboBox.setItemText(39, _translate("ClientInfoModal_2", "PA"))
        self.StateComboBox.setItemText(40, _translate("ClientInfoModal_2", "RI"))
        self.StateComboBox.setItemText(41, _translate("ClientInfoModal_2", "SC"))
        self.StateComboBox.setItemText(42, _translate("ClientInfoModal_2", "SD"))
        self.StateComboBox.setItemText(43, _translate("ClientInfoModal_2", "TN"))
        self.StateComboBox.setItemText(44, _translate("ClientInfoModal_2", "TX"))
        self.StateComboBox.setItemText(45, _translate("ClientInfoModal_2", "UT"))
        self.StateComboBox.setItemText(46, _translate("ClientInfoModal_2", "VA"))
        self.StateComboBox.setItemText(47, _translate("ClientInfoModal_2", "VT"))
        self.StateComboBox.setItemText(48, _translate("ClientInfoModal_2", "VA"))
        self.StateComboBox.setItemText(49, _translate("ClientInfoModal_2", "WA"))
        self.StateComboBox.setItemText(50, _translate("ClientInfoModal_2", "WV"))
        self.StateComboBox.setItemText(51, _translate("ClientInfoModal_2", "WI"))
        self.StateComboBox.setItemText(52, _translate("ClientInfoModal_2", "WY"))
        self.EmailInput.setPlaceholderText(_translate("ClientInfoModal_2", "Email"))
        self.PhoneInput.setPlaceholderText(_translate("ClientInfoModal_2", "Phone"))
        self.HomeSearchURLInput.setPlaceholderText(_translate("ClientInfoModal_2", "Home Search URL"))
        self.HomeValueURLInput.setPlaceholderText(_translate("ClientInfoModal_2", "Home Value URL"))
        self.BlogURLInput.setPlaceholderText(_translate("ClientInfoModal_2", "Blog URL"))
        self.FirstNameInput.setPlaceholderText(_translate("ClientInfoModal_2", "First Name"))
        self.LastNameInput.setPlaceholderText(_translate("ClientInfoModal_2", "Last Name"))
        self.CompanyNameInput.setPlaceholderText(_translate("ClientInfoModal_2", "Company Name"))
        self.Address1Input.setPlaceholderText(_translate("ClientInfoModal_2", "Address 1"))
        self.Address2Input.setPlaceholderText(_translate("ClientInfoModal_2", "Address 2"))
        self.SaveBtn.setText(_translate("ClientInfoModal_2", "Save"))
        self.CancelBtn.setText(_translate("ClientInfoModal_2", "Cancel"))
        self.HexColorInput.setPlaceholderText(_translate("ClientInfoModal_2", "Hex Color"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClientInfoModal_2 = QtWidgets.QDialog()
    ui = Ui_ClientInfoModal_2()
    ui.setupUi(ClientInfoModal_2)
    ClientInfoModal_2.show()
    sys.exit(app.exec_())

