# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mailblender.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MailBlender(object):
    def setupUi(self, MailBlender):
        MailBlender.setObjectName("MailBlender")
        MailBlender.resize(1267, 765)
        self.centralwidget = QtWidgets.QWidget(MailBlender)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(260, 107, 1001, 601))
        self.stackedWidget.setStyleSheet("StackedWidget:(\n"
"border{ 1px solid #fff;}\n"
")")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.HexColorInput = QtWidgets.QLineEdit(self.page)
        self.HexColorInput.setGeometry(QtCore.QRect(480, 410, 131, 32))
        self.HexColorInput.setMinimumSize(QtCore.QSize(0, 30))
        self.HexColorInput.setObjectName("HexColorInput")
        self.StateComboBox = QtWidgets.QComboBox(self.page)
        self.StateComboBox.setGeometry(QtCore.QRect(470, 260, 141, 32))
        self.StateComboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.StateComboBox.setObjectName("StateComboBox")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.HomeSearchURLInput = QtWidgets.QLineEdit(self.page)
        self.HomeSearchURLInput.setGeometry(QtCore.QRect(20, 410, 221, 32))
        self.HomeSearchURLInput.setMinimumSize(QtCore.QSize(0, 30))
        self.HomeSearchURLInput.setObjectName("HomeSearchURLInput")
        self.PhoneInput = QtWidgets.QLineEdit(self.page)
        self.PhoneInput.setGeometry(QtCore.QRect(20, 110, 291, 32))
        self.PhoneInput.setMinimumSize(QtCore.QSize(0, 30))
        self.PhoneInput.setText("")
        self.PhoneInput.setObjectName("PhoneInput")
        self.BlogURLInput = QtWidgets.QLineEdit(self.page)
        self.BlogURLInput.setGeometry(QtCore.QRect(320, 370, 291, 32))
        self.BlogURLInput.setMinimumSize(QtCore.QSize(0, 30))
        self.BlogURLInput.setObjectName("BlogURLInput")
        self.HomeValueURLInput = QtWidgets.QLineEdit(self.page)
        self.HomeValueURLInput.setGeometry(QtCore.QRect(250, 410, 221, 32))
        self.HomeValueURLInput.setMinimumSize(QtCore.QSize(0, 30))
        self.HomeValueURLInput.setObjectName("HomeValueURLInput")
        self.ZipInput = QtWidgets.QLineEdit(self.page)
        self.ZipInput.setGeometry(QtCore.QRect(320, 260, 141, 32))
        self.ZipInput.setMinimumSize(QtCore.QSize(0, 30))
        self.ZipInput.setObjectName("ZipInput")
        self.EmailInput = QtWidgets.QLineEdit(self.page)
        self.EmailInput.setGeometry(QtCore.QRect(320, 110, 291, 32))
        self.EmailInput.setMinimumSize(QtCore.QSize(0, 30))
        self.EmailInput.setObjectName("EmailInput")
        self.LastNameInput = QtWidgets.QLineEdit(self.page)
        self.LastNameInput.setGeometry(QtCore.QRect(320, 30, 291, 32))
        self.LastNameInput.setMinimumSize(QtCore.QSize(0, 30))
        self.LastNameInput.setObjectName("LastNameInput")
        self.CityInput = QtWidgets.QLineEdit(self.page)
        self.CityInput.setGeometry(QtCore.QRect(20, 260, 291, 32))
        self.CityInput.setMinimumSize(QtCore.QSize(0, 30))
        self.CityInput.setObjectName("CityInput")
        self.Address1Input = QtWidgets.QLineEdit(self.page)
        self.Address1Input.setGeometry(QtCore.QRect(20, 220, 291, 32))
        self.Address1Input.setMinimumSize(QtCore.QSize(0, 30))
        self.Address1Input.setObjectName("Address1Input")
        self.Address2Input = QtWidgets.QLineEdit(self.page)
        self.Address2Input.setGeometry(QtCore.QRect(320, 220, 291, 32))
        self.Address2Input.setMinimumSize(QtCore.QSize(0, 30))
        self.Address2Input.setObjectName("Address2Input")
        self.CancelBtn = QtWidgets.QPushButton(self.page)
        self.CancelBtn.setGeometry(QtCore.QRect(910, 560, 84, 34))
        self.CancelBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.CancelBtn.setObjectName("CancelBtn")
        self.SaveBtn = QtWidgets.QPushButton(self.page)
        self.SaveBtn.setGeometry(QtCore.QRect(820, 560, 84, 34))
        self.SaveBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.SaveBtn.setFlat(False)
        self.SaveBtn.setObjectName("SaveBtn")
        self.CompanyNameInput = QtWidgets.QLineEdit(self.page)
        self.CompanyNameInput.setGeometry(QtCore.QRect(20, 70, 591, 32))
        self.CompanyNameInput.setMinimumSize(QtCore.QSize(0, 30))
        self.CompanyNameInput.setObjectName("CompanyNameInput")
        self.FirstNameInput = QtWidgets.QLineEdit(self.page)
        self.FirstNameInput.setGeometry(QtCore.QRect(20, 30, 291, 32))
        self.FirstNameInput.setMinimumSize(QtCore.QSize(0, 30))
        self.FirstNameInput.setProperty("clearButtonEnabled", False)
        self.FirstNameInput.setObjectName("FirstNameInput")
        self.WebsiteURLInput = QtWidgets.QLineEdit(self.page)
        self.WebsiteURLInput.setGeometry(QtCore.QRect(20, 370, 291, 32))
        self.WebsiteURLInput.setMinimumSize(QtCore.QSize(0, 30))
        self.WebsiteURLInput.setObjectName("WebsiteURLInput")
        self.weblinklabel = QtWidgets.QLabel(self.page)
        self.weblinklabel.setGeometry(QtCore.QRect(20, 340, 101, 18))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.weblinklabel.setFont(font)
        self.weblinklabel.setScaledContents(False)
        self.weblinklabel.setObjectName("weblinklabel")
        self.weblinklabel_2 = QtWidgets.QLabel(self.page)
        self.weblinklabel_2.setGeometry(QtCore.QRect(20, 0, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.weblinklabel_2.setFont(font)
        self.weblinklabel_2.setScaledContents(False)
        self.weblinklabel_2.setObjectName("weblinklabel_2")
        self.weblinklabel_3 = QtWidgets.QLabel(self.page)
        self.weblinklabel_3.setGeometry(QtCore.QRect(20, 190, 101, 18))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.weblinklabel_3.setFont(font)
        self.weblinklabel_3.setScaledContents(False)
        self.weblinklabel_3.setObjectName("weblinklabel_3")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.clientListView = QtWidgets.QListView(self.centralwidget)
        self.clientListView.setGeometry(QtCore.QRect(0, 101, 256, 611))
        self.clientListView.setObjectName("clientListView")
        self.stackedWidget.raise_()
        self.clientListView.raise_()
        self.SaveBtn.raise_()
        MailBlender.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MailBlender)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1267, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MailBlender.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MailBlender)
        self.statusbar.setObjectName("statusbar")
        MailBlender.setStatusBar(self.statusbar)
        self.actionAdd_Client = QtWidgets.QAction(MailBlender)
        self.actionAdd_Client.setObjectName("actionAdd_Client")
        self.actionQuit = QtWidgets.QAction(MailBlender)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionAdd_Client)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MailBlender)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MailBlender)

    def retranslateUi(self, MailBlender):
        _translate = QtCore.QCoreApplication.translate
        MailBlender.setWindowTitle(_translate("MailBlender", "MainWindow"))
        self.HexColorInput.setPlaceholderText(_translate("MailBlender", "Hex Color"))
        self.StateComboBox.setItemText(0, _translate("MailBlender", "State"))
        self.StateComboBox.setItemText(1, _translate("MailBlender", "Alabama"))
        self.StateComboBox.setItemText(2, _translate("MailBlender", "Alaska"))
        self.StateComboBox.setItemText(3, _translate("MailBlender", "Arizona"))
        self.StateComboBox.setItemText(4, _translate("MailBlender", "Arkansas"))
        self.StateComboBox.setItemText(5, _translate("MailBlender", "California"))
        self.StateComboBox.setItemText(6, _translate("MailBlender", "Colorado"))
        self.StateComboBox.setItemText(7, _translate("MailBlender", "Connecticut"))
        self.StateComboBox.setItemText(8, _translate("MailBlender", "Delaware"))
        self.StateComboBox.setItemText(9, _translate("MailBlender", "Florida"))
        self.StateComboBox.setItemText(10, _translate("MailBlender", "Georgia"))
        self.StateComboBox.setItemText(11, _translate("MailBlender", "Hawaii"))
        self.StateComboBox.setItemText(12, _translate("MailBlender", "Idaho"))
        self.StateComboBox.setItemText(13, _translate("MailBlender", "Illinois"))
        self.StateComboBox.setItemText(14, _translate("MailBlender", "Indiana"))
        self.StateComboBox.setItemText(15, _translate("MailBlender", "Iowa"))
        self.StateComboBox.setItemText(16, _translate("MailBlender", "Kansas"))
        self.StateComboBox.setItemText(17, _translate("MailBlender", "Kentucky"))
        self.StateComboBox.setItemText(18, _translate("MailBlender", "Louisiana"))
        self.StateComboBox.setItemText(19, _translate("MailBlender", "Maine"))
        self.StateComboBox.setItemText(20, _translate("MailBlender", "Maryland"))
        self.StateComboBox.setItemText(21, _translate("MailBlender", "Massachusetts"))
        self.StateComboBox.setItemText(22, _translate("MailBlender", "Michigan"))
        self.StateComboBox.setItemText(23, _translate("MailBlender", "Minnesota"))
        self.StateComboBox.setItemText(24, _translate("MailBlender", "Mississippi"))
        self.StateComboBox.setItemText(25, _translate("MailBlender", "Missouri"))
        self.StateComboBox.setItemText(26, _translate("MailBlender", "Montana"))
        self.StateComboBox.setItemText(27, _translate("MailBlender", "Nebraska"))
        self.StateComboBox.setItemText(28, _translate("MailBlender", "Nevada"))
        self.StateComboBox.setItemText(29, _translate("MailBlender", "New Hampshire"))
        self.StateComboBox.setItemText(30, _translate("MailBlender", "New Jersey"))
        self.StateComboBox.setItemText(31, _translate("MailBlender", "New Mexico"))
        self.StateComboBox.setItemText(32, _translate("MailBlender", "New York"))
        self.StateComboBox.setItemText(33, _translate("MailBlender", "North Carolina"))
        self.StateComboBox.setItemText(34, _translate("MailBlender", "North Dakota"))
        self.StateComboBox.setItemText(35, _translate("MailBlender", "Ohio"))
        self.StateComboBox.setItemText(36, _translate("MailBlender", "Oklahoma"))
        self.StateComboBox.setItemText(37, _translate("MailBlender", "Oregon"))
        self.StateComboBox.setItemText(38, _translate("MailBlender", "Pennsylvania"))
        self.StateComboBox.setItemText(39, _translate("MailBlender", "Rhode Island"))
        self.StateComboBox.setItemText(40, _translate("MailBlender", "South Carolina"))
        self.StateComboBox.setItemText(41, _translate("MailBlender", "South Dakota"))
        self.StateComboBox.setItemText(42, _translate("MailBlender", "Tennessee"))
        self.StateComboBox.setItemText(43, _translate("MailBlender", "Texas"))
        self.StateComboBox.setItemText(44, _translate("MailBlender", "Utah"))
        self.StateComboBox.setItemText(45, _translate("MailBlender", "Vermont"))
        self.StateComboBox.setItemText(46, _translate("MailBlender", "Virginia"))
        self.StateComboBox.setItemText(47, _translate("MailBlender", "Washington"))
        self.StateComboBox.setItemText(48, _translate("MailBlender", "West Virginia"))
        self.StateComboBox.setItemText(49, _translate("MailBlender", "Wisconsin"))
        self.StateComboBox.setItemText(50, _translate("MailBlender", "Wyoming"))
        self.HomeSearchURLInput.setPlaceholderText(_translate("MailBlender", "Home Search URL"))
        self.PhoneInput.setPlaceholderText(_translate("MailBlender", "Phone"))
        self.BlogURLInput.setPlaceholderText(_translate("MailBlender", "Blog URL"))
        self.HomeValueURLInput.setPlaceholderText(_translate("MailBlender", "Home Value URL"))
        self.ZipInput.setPlaceholderText(_translate("MailBlender", "Zip"))
        self.EmailInput.setPlaceholderText(_translate("MailBlender", "Email"))
        self.LastNameInput.setPlaceholderText(_translate("MailBlender", "Last Name"))
        self.CityInput.setPlaceholderText(_translate("MailBlender", "City"))
        self.Address1Input.setPlaceholderText(_translate("MailBlender", "Address 1"))
        self.Address2Input.setPlaceholderText(_translate("MailBlender", "Address 2"))
        self.CancelBtn.setText(_translate("MailBlender", "Cancel"))
        self.SaveBtn.setText(_translate("MailBlender", "Save"))
        self.CompanyNameInput.setPlaceholderText(_translate("MailBlender", "Company Name"))
        self.FirstNameInput.setPlaceholderText(_translate("MailBlender", "First Name"))
        self.WebsiteURLInput.setPlaceholderText(_translate("MailBlender", "Website URL"))
        self.weblinklabel.setText(_translate("MailBlender", "Web"))
        self.weblinklabel_2.setText(_translate("MailBlender", "Contact"))
        self.weblinklabel_3.setText(_translate("MailBlender", "Address"))
        self.menuFile.setTitle(_translate("MailBlender", "File"))
        self.actionAdd_Client.setText(_translate("MailBlender", "Add Client"))
        self.actionQuit.setText(_translate("MailBlender", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MailBlender = QtWidgets.QMainWindow()
    ui = Ui_MailBlender()
    ui.setupUi(MailBlender)
    MailBlender.show()
    sys.exit(app.exec_())

