# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mailblender.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MailBlender(object):
    def setupUi(self, MailBlender):
        MailBlender.setObjectName("MailBlender")
        MailBlender.resize(1267, 765)
        self.centralwidget = QtWidgets.QWidget(MailBlender)
        self.centralwidget.setObjectName("centralwidget")
        self.MainContentWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.MainContentWidget.setGeometry(QtCore.QRect(260, 97, 1001, 611))
        self.MainContentWidget.setStyleSheet("")
        self.MainContentWidget.setObjectName("MainContentWidget")
        self.AddClientPage = QtWidgets.QWidget()
        self.AddClientPage.setObjectName("AddClientPage")
        self.StateComboBox = QtWidgets.QComboBox(self.AddClientPage)
        self.StateComboBox.setGeometry(QtCore.QRect(470, 240, 141, 30))
        self.StateComboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.StateComboBox.setObjectName("StateComboBox")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.StateComboBox.addItem("")
        self.HomeSearchURLInput = QtWidgets.QLineEdit(self.AddClientPage)
        self.HomeSearchURLInput.setGeometry(QtCore.QRect(20, 370, 221, 30))
        self.HomeSearchURLInput.setMinimumSize(QtCore.QSize(0, 30))
        self.HomeSearchURLInput.setObjectName("HomeSearchURLInput")
        self.PhoneInput = QtWidgets.QLineEdit(self.AddClientPage)
        self.PhoneInput.setGeometry(QtCore.QRect(20, 110, 291, 30))
        self.PhoneInput.setMinimumSize(QtCore.QSize(0, 30))
        self.PhoneInput.setText("")
        self.PhoneInput.setObjectName("PhoneInput")
        self.BlogURLInput = QtWidgets.QLineEdit(self.AddClientPage)
        self.BlogURLInput.setGeometry(QtCore.QRect(320, 330, 291, 30))
        self.BlogURLInput.setMinimumSize(QtCore.QSize(0, 30))
        self.BlogURLInput.setObjectName("BlogURLInput")
        self.HomeValueURLInput = QtWidgets.QLineEdit(self.AddClientPage)
        self.HomeValueURLInput.setGeometry(QtCore.QRect(250, 370, 221, 30))
        self.HomeValueURLInput.setMinimumSize(QtCore.QSize(0, 30))
        self.HomeValueURLInput.setObjectName("HomeValueURLInput")
        self.ZipInput = QtWidgets.QLineEdit(self.AddClientPage)
        self.ZipInput.setGeometry(QtCore.QRect(320, 240, 141, 30))
        self.ZipInput.setMinimumSize(QtCore.QSize(0, 30))
        self.ZipInput.setObjectName("ZipInput")
        self.EmailInput = QtWidgets.QLineEdit(self.AddClientPage)
        self.EmailInput.setGeometry(QtCore.QRect(320, 110, 291, 30))
        self.EmailInput.setMinimumSize(QtCore.QSize(0, 30))
        self.EmailInput.setObjectName("EmailInput")
        self.LastNameInput = QtWidgets.QLineEdit(self.AddClientPage)
        self.LastNameInput.setGeometry(QtCore.QRect(320, 30, 291, 30))
        self.LastNameInput.setMinimumSize(QtCore.QSize(0, 30))
        self.LastNameInput.setObjectName("LastNameInput")
        self.CityInput = QtWidgets.QLineEdit(self.AddClientPage)
        self.CityInput.setGeometry(QtCore.QRect(20, 240, 291, 30))
        self.CityInput.setMinimumSize(QtCore.QSize(0, 30))
        self.CityInput.setObjectName("CityInput")
        self.Address1Input = QtWidgets.QLineEdit(self.AddClientPage)
        self.Address1Input.setGeometry(QtCore.QRect(20, 200, 291, 30))
        self.Address1Input.setMinimumSize(QtCore.QSize(0, 30))
        self.Address1Input.setObjectName("Address1Input")
        self.Address2Input = QtWidgets.QLineEdit(self.AddClientPage)
        self.Address2Input.setGeometry(QtCore.QRect(320, 200, 291, 30))
        self.Address2Input.setMinimumSize(QtCore.QSize(0, 30))
        self.Address2Input.setObjectName("Address2Input")
        self.CancelBtn = QtWidgets.QPushButton(self.AddClientPage)
        self.CancelBtn.setGeometry(QtCore.QRect(910, 560, 84, 34))
        self.CancelBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.CancelBtn.setObjectName("CancelBtn")
        self.SaveBtn = QtWidgets.QPushButton(self.AddClientPage)
        self.SaveBtn.setGeometry(QtCore.QRect(820, 560, 84, 34))
        self.SaveBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.SaveBtn.setFlat(False)
        self.SaveBtn.setObjectName("SaveBtn")
        self.CompanyNameInput = QtWidgets.QLineEdit(self.AddClientPage)
        self.CompanyNameInput.setGeometry(QtCore.QRect(20, 70, 591, 30))
        self.CompanyNameInput.setMinimumSize(QtCore.QSize(0, 30))
        self.CompanyNameInput.setObjectName("CompanyNameInput")
        self.FirstNameInput = QtWidgets.QLineEdit(self.AddClientPage)
        self.FirstNameInput.setGeometry(QtCore.QRect(20, 30, 291, 30))
        self.FirstNameInput.setMinimumSize(QtCore.QSize(0, 30))
        self.FirstNameInput.setProperty("clearButtonEnabled", False)
        self.FirstNameInput.setObjectName("FirstNameInput")
        self.WebsiteURLInput = QtWidgets.QLineEdit(self.AddClientPage)
        self.WebsiteURLInput.setGeometry(QtCore.QRect(20, 330, 291, 30))
        self.WebsiteURLInput.setMinimumSize(QtCore.QSize(0, 30))
        self.WebsiteURLInput.setObjectName("WebsiteURLInput")
        self.WebLabel = QtWidgets.QLabel(self.AddClientPage)
        self.WebLabel.setGeometry(QtCore.QRect(22, 300, 101, 18))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.WebLabel.setFont(font)
        self.WebLabel.setScaledContents(False)
        self.WebLabel.setObjectName("WebLabel")
        self.ContactLabel = QtWidgets.QLabel(self.AddClientPage)
        self.ContactLabel.setGeometry(QtCore.QRect(22, 0, 191, 18))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ContactLabel.setFont(font)
        self.ContactLabel.setScaledContents(False)
        self.ContactLabel.setObjectName("ContactLabel")
        self.AddressLAbel = QtWidgets.QLabel(self.AddClientPage)
        self.AddressLAbel.setGeometry(QtCore.QRect(22, 170, 101, 18))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.AddressLAbel.setFont(font)
        self.AddressLAbel.setScaledContents(False)
        self.AddressLAbel.setObjectName("AddressLAbel")
        self.HeaderLogoLabel = QtWidgets.QLabel(self.AddClientPage)
        self.HeaderLogoLabel.setGeometry(QtCore.QRect(630, -10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.HeaderLogoLabel.setFont(font)
        self.HeaderLogoLabel.setScaledContents(False)
        self.HeaderLogoLabel.setObjectName("HeaderLogoLabel")
        self.FooterLogoLabel = QtWidgets.QLabel(self.AddClientPage)
        self.FooterLogoLabel.setGeometry(QtCore.QRect(630, 290, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.FooterLogoLabel.setFont(font)
        self.FooterLogoLabel.setScaledContents(False)
        self.FooterLogoLabel.setObjectName("FooterLogoLabel")
        self.BannerImageLabel = QtWidgets.QLabel(self.AddClientPage)
        self.BannerImageLabel.setGeometry(QtCore.QRect(22, 420, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.BannerImageLabel.setFont(font)
        self.BannerImageLabel.setScaledContents(False)
        self.BannerImageLabel.setObjectName("BannerImageLabel")
        self.hexColorFrame = QtWidgets.QFrame(self.AddClientPage)
        self.hexColorFrame.setGeometry(QtCore.QRect(480, 370, 131, 30))
        self.hexColorFrame.setStyleSheet("")
        self.hexColorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hexColorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hexColorFrame.setObjectName("hexColorFrame")
        self.HexColorInput = QtWidgets.QLineEdit(self.hexColorFrame)
        self.HexColorInput.setGeometry(QtCore.QRect(0, 0, 91, 30))
        self.HexColorInput.setMinimumSize(QtCore.QSize(0, 30))
        self.HexColorInput.setStyleSheet("HexColorInput:(\n"
"border-right: none;\n"
")")
        self.HexColorInput.setObjectName("HexColorInput")
        self.MainContentWidget.addWidget(self.AddClientPage)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.MainContentWidget.addWidget(self.page_2)
        self.ClientListLabel = QtWidgets.QLabel(self.centralwidget)
        self.ClientListLabel.setGeometry(QtCore.QRect(12, 100, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ClientListLabel.setFont(font)
        self.ClientListLabel.setScaledContents(False)
        self.ClientListLabel.setObjectName("ClientListLabel")
        self.clientListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.clientListWidget.setGeometry(QtCore.QRect(10, 127, 256, 581))
        self.clientListWidget.setObjectName("clientListWidget")
        self.MainContentWidget.raise_()
        self.SaveBtn.raise_()
        self.ClientListLabel.raise_()
        self.clientListWidget.raise_()
        MailBlender.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MailBlender)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1267, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MailBlender.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MailBlender)
        self.statusbar.setObjectName("statusbar")
        MailBlender.setStatusBar(self.statusbar)
        self.actionAdd_Client = QtWidgets.QAction(MailBlender)
        self.actionAdd_Client.setObjectName("actionAdd_Client")
        self.actionQuit = QtWidgets.QAction(MailBlender)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionAdd_Client)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MailBlender)
        self.MainContentWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MailBlender)
        MailBlender.setTabOrder(self.FirstNameInput, self.LastNameInput)
        MailBlender.setTabOrder(self.LastNameInput, self.CompanyNameInput)
        MailBlender.setTabOrder(self.CompanyNameInput, self.PhoneInput)
        MailBlender.setTabOrder(self.PhoneInput, self.EmailInput)
        MailBlender.setTabOrder(self.EmailInput, self.Address1Input)
        MailBlender.setTabOrder(self.Address1Input, self.Address2Input)
        MailBlender.setTabOrder(self.Address2Input, self.CityInput)
        MailBlender.setTabOrder(self.CityInput, self.ZipInput)
        MailBlender.setTabOrder(self.ZipInput, self.StateComboBox)
        MailBlender.setTabOrder(self.StateComboBox, self.WebsiteURLInput)
        MailBlender.setTabOrder(self.WebsiteURLInput, self.BlogURLInput)
        MailBlender.setTabOrder(self.BlogURLInput, self.HomeSearchURLInput)
        MailBlender.setTabOrder(self.HomeSearchURLInput, self.HomeValueURLInput)
        MailBlender.setTabOrder(self.HomeValueURLInput, self.HexColorInput)
        MailBlender.setTabOrder(self.HexColorInput, self.SaveBtn)
        MailBlender.setTabOrder(self.SaveBtn, self.CancelBtn)

    def retranslateUi(self, MailBlender):
        _translate = QtCore.QCoreApplication.translate
        MailBlender.setWindowTitle(_translate("MailBlender", "MailBlender"))
        self.StateComboBox.setItemText(0, _translate("MailBlender", "State"))
        self.StateComboBox.setItemText(1, _translate("MailBlender", "Alabama"))
        self.StateComboBox.setItemText(2, _translate("MailBlender", "Alaska"))
        self.StateComboBox.setItemText(3, _translate("MailBlender", "Arizona"))
        self.StateComboBox.setItemText(4, _translate("MailBlender", "Arkansas"))
        self.StateComboBox.setItemText(5, _translate("MailBlender", "California"))
        self.StateComboBox.setItemText(6, _translate("MailBlender", "Colorado"))
        self.StateComboBox.setItemText(7, _translate("MailBlender", "Connecticut"))
        self.StateComboBox.setItemText(8, _translate("MailBlender", "Delaware"))
        self.StateComboBox.setItemText(9, _translate("MailBlender", "Florida"))
        self.StateComboBox.setItemText(10, _translate("MailBlender", "Georgia"))
        self.StateComboBox.setItemText(11, _translate("MailBlender", "Hawaii"))
        self.StateComboBox.setItemText(12, _translate("MailBlender", "Idaho"))
        self.StateComboBox.setItemText(13, _translate("MailBlender", "Illinois"))
        self.StateComboBox.setItemText(14, _translate("MailBlender", "Indiana"))
        self.StateComboBox.setItemText(15, _translate("MailBlender", "Iowa"))
        self.StateComboBox.setItemText(16, _translate("MailBlender", "Kansas"))
        self.StateComboBox.setItemText(17, _translate("MailBlender", "Kentucky"))
        self.StateComboBox.setItemText(18, _translate("MailBlender", "Louisiana"))
        self.StateComboBox.setItemText(19, _translate("MailBlender", "Maine"))
        self.StateComboBox.setItemText(20, _translate("MailBlender", "Maryland"))
        self.StateComboBox.setItemText(21, _translate("MailBlender", "Massachusetts"))
        self.StateComboBox.setItemText(22, _translate("MailBlender", "Michigan"))
        self.StateComboBox.setItemText(23, _translate("MailBlender", "Minnesota"))
        self.StateComboBox.setItemText(24, _translate("MailBlender", "Mississippi"))
        self.StateComboBox.setItemText(25, _translate("MailBlender", "Missouri"))
        self.StateComboBox.setItemText(26, _translate("MailBlender", "Montana"))
        self.StateComboBox.setItemText(27, _translate("MailBlender", "Nebraska"))
        self.StateComboBox.setItemText(28, _translate("MailBlender", "Nevada"))
        self.StateComboBox.setItemText(29, _translate("MailBlender", "New Hampshire"))
        self.StateComboBox.setItemText(30, _translate("MailBlender", "New Jersey"))
        self.StateComboBox.setItemText(31, _translate("MailBlender", "New Mexico"))
        self.StateComboBox.setItemText(32, _translate("MailBlender", "New York"))
        self.StateComboBox.setItemText(33, _translate("MailBlender", "North Carolina"))
        self.StateComboBox.setItemText(34, _translate("MailBlender", "North Dakota"))
        self.StateComboBox.setItemText(35, _translate("MailBlender", "Ohio"))
        self.StateComboBox.setItemText(36, _translate("MailBlender", "Oklahoma"))
        self.StateComboBox.setItemText(37, _translate("MailBlender", "Oregon"))
        self.StateComboBox.setItemText(38, _translate("MailBlender", "Pennsylvania"))
        self.StateComboBox.setItemText(39, _translate("MailBlender", "Rhode Island"))
        self.StateComboBox.setItemText(40, _translate("MailBlender", "South Carolina"))
        self.StateComboBox.setItemText(41, _translate("MailBlender", "South Dakota"))
        self.StateComboBox.setItemText(42, _translate("MailBlender", "Tennessee"))
        self.StateComboBox.setItemText(43, _translate("MailBlender", "Texas"))
        self.StateComboBox.setItemText(44, _translate("MailBlender", "Utah"))
        self.StateComboBox.setItemText(45, _translate("MailBlender", "Vermont"))
        self.StateComboBox.setItemText(46, _translate("MailBlender", "Virginia"))
        self.StateComboBox.setItemText(47, _translate("MailBlender", "Washington"))
        self.StateComboBox.setItemText(48, _translate("MailBlender", "West Virginia"))
        self.StateComboBox.setItemText(49, _translate("MailBlender", "Wisconsin"))
        self.StateComboBox.setItemText(50, _translate("MailBlender", "Wyoming"))
        self.HomeSearchURLInput.setPlaceholderText(_translate("MailBlender", "Home Search URL"))
        self.PhoneInput.setPlaceholderText(_translate("MailBlender", "Phone"))
        self.BlogURLInput.setPlaceholderText(_translate("MailBlender", "Blog URL"))
        self.HomeValueURLInput.setPlaceholderText(_translate("MailBlender", "Home Value URL"))
        self.ZipInput.setPlaceholderText(_translate("MailBlender", "Zip"))
        self.EmailInput.setPlaceholderText(_translate("MailBlender", "Email"))
        self.LastNameInput.setPlaceholderText(_translate("MailBlender", "Last Name"))
        self.CityInput.setPlaceholderText(_translate("MailBlender", "City"))
        self.Address1Input.setPlaceholderText(_translate("MailBlender", "Address 1"))
        self.Address2Input.setPlaceholderText(_translate("MailBlender", "Address 2"))
        self.CancelBtn.setText(_translate("MailBlender", "Cancel"))
        self.SaveBtn.setText(_translate("MailBlender", "Save"))
        self.CompanyNameInput.setPlaceholderText(_translate("MailBlender", "Company Name"))
        self.FirstNameInput.setPlaceholderText(_translate("MailBlender", "First Name"))
        self.WebsiteURLInput.setPlaceholderText(_translate("MailBlender", "Website URL"))
        self.WebLabel.setText(_translate("MailBlender", "Web"))
        self.ContactLabel.setText(_translate("MailBlender", "Contact"))
        self.AddressLAbel.setText(_translate("MailBlender", "Address"))
        self.HeaderLogoLabel.setText(_translate("MailBlender", "Header Logo"))
        self.FooterLogoLabel.setText(_translate("MailBlender", "Footer  Logo"))
        self.BannerImageLabel.setText(_translate("MailBlender", "Banner Image"))
        self.HexColorInput.setPlaceholderText(_translate("MailBlender", "Hex Color"))
        self.ClientListLabel.setText(_translate("MailBlender", "Client List"))
        self.menuFile.setTitle(_translate("MailBlender", "File"))
        self.actionAdd_Client.setText(_translate("MailBlender", "Add Client"))
        self.actionQuit.setText(_translate("MailBlender", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MailBlender = QtWidgets.QMainWindow()
    ui = Ui_MailBlender()
    ui.setupUi(MailBlender)
    MailBlender.show()
    sys.exit(app.exec_())

